#    $$$$$$$\  $$$$$$$\   $$$$$$\  $$$$$$$\   $$$$$$\  $$\      $$\ $$$$$$$\
#    $$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\ $$$\    $$$ |$$  __$$\
#    $$ |  $$ |$$ |  $$ |$$ /  $$ |$$ |  $$ |$$ /  \__|$$$$\  $$$$ |$$ |  $$ |
#    $$ |  $$ |$$$$$$$  |$$ |  $$ |$$$$$$$  |\$$$$$$\  $$\$$\$$ $$ |$$$$$$$  |
#    $$ |  $$ |$$  __$$< $$ |  $$ |$$  ____/  \____$$\ $$ \$$$  $$ |$$  ____/
#    $$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |      $$\   $$ |$$ |\$  /$$ |$$ |
#    $$$$$$$  |$$ |  $$ | $$$$$$  |$$ |      \$$$$$$  |$$ | \_/ $$ |$$ |
#    \_______/ \__|  \__| \______/ \__|       \______/ \__|     \__|\__|

#       Informacje o autorze
# ogladam anime#9438
# https://discord.gg/pfD9VbDSNU
# Wersja: 1.3
# Wersja pluginu: PREMIUM

#Jak ma wyglÄ…daÄ‡ actionbar?
actionbar: "Â§câš” {0}%    Â§7ðŸ›¡ {1}%    Â§bâš¡ {2}%"

#Na ila ma byÄ‡ ban za stratÄ™ wszystkich statystyk? Czas podany w godzinach (dziaÅ‚a tylko gdy use-external-ban-command jest na false)
ban-time-hours: 24

#Czy ban ma byÄ‡ z zewnÄ™trznej komendy? (np. Essentials etc.)
use-external-ban-command: false

#Jak ma wyglÄ…daÄ‡ komenda banowania gracza po smierci?
external-ban-command: "ban {0} ZostaÅ‚eÅ› zabity!"

#Czy unban ma byÄ‡ z zewnÄ™trznej komendy? (np. Essentials etc.) Musi byÄ‡ jeÅ¼eli ban jeest z zewnÄ™trznej komendy!!
use-external-unban-command: false

#Jak ma wyglÄ…daÄ‡ komenda odbanowania gracza po wskrzeszeniu?
external-unban-command: "unban {0}"

#Jak ma wyglÄ…daÄ‡ insygnia? Wszystkie infomacje
insygnia:
  itemtype: PAPER
  name: "Â§8â—† Â§dÂ§lINSYGNIA ODNOWIENIA"
  lore:
    - ' '
    - '          Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†'
    - ''
    - '  Â§8â—† Â§7Resetuje wszystkie statystyki do 100% Â§8â—†    '
    - '   Â§8â—† Â§eKliknij prawym, aby uÅ¼yÄ‡ przedmiotu Â§8â—†    '
  glowing: true
  crafting:
    status: true
    slot1: AIR
    slot2: GHAST_TEAR
    slot3: AIR
    slot4: GHAST_TEAR
    slot5: GOLD_BLOCK
    slot6: GHAST_TEAR
    slot7: AIR
    slot8: GHAST_TEAR
    slot9: AIR

#Jak majÄ… wyglÄ…daÄ‡ emblematy? Wszystkie informacje
#limit: 250 #ile ma wynosiÄ‡ limit statystki dla gracza
#glowing: true #czy przedmiot ma byÄ‡ enchantowany
#gain-value: 10 #ile procent ma dawaÄ‡ uÅ¼ycie przedmiotu
emblematy:
  strength:
    limit: 250
    gain-value: 10
    itemtype: PAPER
    name: "Â§8â—† Â§cÂ§lEMBLEMAT SIÅY"
    lore:
      - " "
      - "          Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "   Â§8â—† Â§7Podnosi statystykÄ™ siÅ‚y o 10% Â§8â—†    "
      - "   Â§8â—† Â§eKliknij prawym, aby uÅ¼yÄ‡ przedmiotu Â§8â—†    "
    glowing: true
  protection:
    limit: 250
    gain-value: 10
    itemtype: PAPER
    name: "Â§8â—† Â§7Â§lEMBLEMAT OBRONY"
    lore:
      - " "
      - "          Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "   Â§8â—† Â§7Podnosi statystykÄ™ obrony o 10% Â§8â—†    "
      - "   Â§8â—† Â§eKliknij prawym, aby uÅ¼yÄ‡ przedmiotu Â§8â—†    "
    glowing: true
  speed:
    limit: 250
    gain-value: 10
    itemtype: PAPER
    name: "Â§8â—† Â§bÂ§lEMBLEMAT SZYBKOÅšCI"
    lore:
      - " "
      - "          Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "   Â§8â—† Â§7Podnosi statystykÄ™ szybkoÅ›ci o 10% Â§8â—†    "
      - "   Â§8â—† Â§eKliknij prawym, aby uÅ¼yÄ‡ przedmiotu Â§8â—†    "
    glowing: true

#Jak ma wyglÄ…daÄ‡ lootbox? Wszystkie inforamcje i procenty na drop
mysterybox:
  name: "Â§8â—† Â§3Â§lLOOTBOX"
  lore:
    - " "
    - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
    - ""
    - "  Â§8â—† Â§7Pozwala na wylosowanie magicznego przedmiotu! Â§8â—†    "
    - "         Â§8â—† Â§eKliknij prawym, aby uÅ¼yÄ‡ przedmiotu Â§8â—†    "
  glowing: true
  #Jak ma wyglÄ…daÄ‡ mysterybox? Podaj link do skina. (https://minecraft-heads.com/)
  skin-url: "https://textures.minecraft.net/texture/ac4970ea91ab06ece59d45fce7604d255431f2e03a737b226082c4cce1aca1c4"
  drops:
    #Jakie przedmioty majÄ… znajdowaÄ‡ siÄ™ w dropie?
    #Lista przedmiotÃ³w: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    #WyglÄ…d dodawanego przedmiotu: ITEM ILOÅšÄ† ENCHANTY name:NAZWA_PRZEDMIOTU lore:OPIS|DRUGA_LINIJKA
    - "PAPER 1 DURABILITY:1 name:&8â—†_&d&lINSYGNIA_ODNOWIENIA lore:_|__________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||__&8â—†_&7Resetuje_wszystkie_statystyki_do_100%_&8â—†____|___&8â—†_&eKliknij_prawym,_aby_uÅ¼yÄ‡_przedmiotu_&8â—†____"
    - "PAPER 1 DURABILITY:1 name:&8â—†_&c&lEMBLEMAT_SIÅY lore:_|__________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||___&8â—†_&7Podnosi_statystykÄ™_siÅ‚y_o_10%_&8â—†____|___&8â—†_&eKliknij_prawym,_aby_uÅ¼yÄ‡_przedmiotu_&8â—†____"
    - "PAPER 1 DURABILITY:1 name:&8â—†_&7&lEMBLEMAT_OBRONY lore:_|__________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||___&8â—†_&7Podnosi_statystykÄ™_obrony_o_10%_&8â—†____|___&8â—†_&eKliknij_prawym,_aby_uÅ¼yÄ‡_przedmiotu_&8â—†____"
    - "PAPER 1 DURABILITY:1 name:&8â—†_&b&lEMBLEMAT_SZYBKOÅšCI lore:_|__________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||___&8â—†_&7Podnosi_statystykÄ™_szybkoÅ›ci_o_10%_&8â—†____|___&8â—†_&eKliknij_prawym,_aby_uÅ¼yÄ‡_przedmiotu_&8â—†____"
    - "DIAMOND_PICKAXE 1 DURABILITY:1 name:&8â—†_&6&lKilof_szybkoÅ›ci lore:_|_____________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||__&8â—†_&7Podczas_trzymania_w_rÄ™ku_nadaje_efekt_HASTE!_&8â—†____"
    - "DIAMOND_PICKAXE 1 DURABILITY:1 name:&8â—†_&b&lKilof_3x3 lore:_|_____________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||__&8â—†_&7Wykopanie_bloku_spowoduje_zniszczenie_blokÃ³w_3x3!_&8â—†____"
    - "DIAMOND_SWORD 1 DAMAGE_ALL:1 name:&8â—†_&2&lZatruty_miecz lore:_|_____________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||__&8â—†_&7Co_10_sekund_nakÅ‚ada_efekt_zatrucia!_&8â—†____"
    - "DIAMOND_AXE 1 DURABILITY:1 name:&8â—†_&9&lMagiczna_siekiera lore:_|_____________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||__&8â—†_&7Co_5_sekund_przy_ataku_nakÅ‚ada_piorun!_&8â—†____"
    - "RED_DYE 1 DURABILITY:1 name:&8â—†_&c&lDodatkowe_serce lore:_|_____________&8â—†_&b&lFUNKCJA_PRZEDMIOTU_&8â—†||__&8â—†_&7Dodaje_dodatkowe_staÅ‚e_serce!_&8â—†____"
  #Szansa na drop gÅ‚owy po zabiciu gracza
  chance-for-drop: 50

#Ile ma trwaÄ‡ cooldown na drop lootboxa po zabiciu gracza? Czas podaj w sekundach
next-drop-time: 3600

#Specjalne przedmioty i ich ustawienia
magic-items:
  #Kilof szybkoÅ›ci
  haste-pickaxe:
    itemtype: DIAMOND_PICKAXE
    name: "Â§8â—† Â§6Â§lKilof szybkoÅ›ci"
    lore:
    - " "
    - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
    - ""
    - "  Â§8â—† Â§7Podczas trzymania w rÄ™ku nadaje efekt HASTE! Â§8â—†    "
    unbreaking-1: true
  #Kilof szybkoÅ›ci
  3x3-pickaxe:
    itemtype: DIAMOND_PICKAXE
    name: "Â§8â—† Â§bÂ§lKilof 3x3"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Wykopanie bloku spowoduje zniszczenie blokÃ³w 3x3! Â§8â—†    "
    unbreaking-1: true
  #Zatruty miecz
  poison-sword:
    itemtype: DIAMOND_SWORD
    name: "Â§8â—† Â§2Â§lZatruty miecz"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Co 10 sekund nakÅ‚ada efekt zatrucia! Â§8â—†    "
    sharpness-1: true
    #Cooldown w sekundach
    cooldown: 10
  magic-axe:
    itemtype: DIAMOND_AXE
    name: "Â§8â—† Â§9Â§lMagiczna siekiera"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Co 5 sekund przy ataku nakÅ‚ada piorun! Â§8â—†    "
    unbreaking-1: true
    #Cooldown w sekundach
    cooldown: 5
  heart:
    itemtype: RED_DYE
    name: "Â§8â—† Â§cÂ§lDodatkowe serce"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Dodaje dodatkowe staÅ‚e serce! Â§8â—†    "
    unbreaking-1: true
    #Ile ma wynosiÄ‡ limit serc?
    limit: 20
  sword-speed:
    itemtype: DIAMOND_SWORD
    name: "Â§8â—† Â§bÂ§lMiecz szybkoÅ›ci"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Co 10 sekund nakÅ‚ada efekt szybkoÅ›ci! Â§8â—†    "
    sharpness-1: true
    #Cooldown w sekundach
    cooldown: 10
  flaming-boots:
    itemtype: DIAMOND_BOOTS
    name: "Â§8â—† Â§6Â§lPÅ‚omienne buty"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Pozwala chodziÄ‡ po lawie! Â§8â—†    "
    unbreaking-1: true
  tribal-chest:
    itemtype: DIAMOND_CHESTPLATE
    name: "Â§8â—† Â§aÂ§lPlemienna zbroja"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Dodaje 2 dodatkowe serca podczas noszenia! Â§8â—†    "
    unbreaking-1: true
    heart-add: 2
  nausea-sword:
    itemtype: DIAMOND_SWORD
    name: "Â§8â—† Â§5Â§lMiecz mdÅ‚oÅ›ci"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Co 10 sekund nakÅ‚ada efekt mdÅ‚oÅ›ci! Â§8â—†    "
    sharpness-1: true
    #Cooldown w sekundach
    cooldown: 10
  lifesteal-sword:
    itemtype: DIAMOND_SWORD
    name: "Â§8â—† Â§cÂ§lMiecz krwiopijcy"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Co 10 sekund dodaje dodatkowe serce! Â§8â—†    "
    sharpness-1: true
    #Cooldown w sekundach
    cooldown: 10
  slowness-axe:
    itemtype: DIAMOND_AXE
    name: "Â§8â—† Â§bÂ§lSiekiera spowolnienia"
    lore:
      - " "
      - "             Â§8â—† Â§bÂ§lFUNKCJA PRZEDMIOTU Â§8â—†"
      - ""
      - "  Â§8â—† Â§7Co 10 sekund nakÅ‚ada efekt spowolnienia! Â§8â—†    "
    unbreaking-1: true
    #Cooldown w sekundach
    cooldown: 10